AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Name Rest API

Parameters:
  AppName:
    Type: String
    Description: Application Name. Used for naming resources

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Layers:
      - !Ref LambdaLayer
    Environment:
      Variables:
        EMPLOYEES_DDB_TABLE: !Ref EmployeesDDBTable
# lambda layer and dynmodb table
Resources:
  EmployeesDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AppName}-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: dob
          AttributeType: N
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: dob
          KeyType: RANGE
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AppName}-lambda-layer'
      Description: !Sub '${AppName} Lambda Layer'
      ContentUri: lambda-layer/
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: cloudwatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource:
                  - '*'
        - PolicyName: ddbaccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmployeesDDBTable}/*'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EmployeesDDBTable}'
  GetData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AppName}-get-data'
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Description: Get employee data from Dynamo DB
      CodeUri: functions/get-data/
      Role:
        Fn::GetAtt: LambdaRole.Arn
 
Outputs:
  GetDataArn:
    Description: ARN of Get Data Lambda Function
    Value: !GetAtt GetData.Arn
    Export:
      Name: !Sub '${AppName}-get-data-arn'
  
